### ISSUE TITLE
java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.AttributeContainerMap

### ISSUE THREAD

**Issue by rahulpandeycs** [openmessaging/openmessaging-benchmark#192]
```
 benchmark-worker.service - Benchmark worker
   Loaded: loaded (/etc/systemd/system/benchmark-worker.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-07-24 19:53:33 UTC; 1s ago
 Main PID: 3985 (java)
   CGroup: /system.slice/benchmark-worker.service
           └─3985 java -server -cp :lib/* -Xms1G -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:Para...

Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at org.eclipse.jetty.server.Server.<init>(Server.java:79)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at org.eclipse.jetty.server.Server.<init>(Server.java:122)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider.start(PrometheusMetricsProvider.java:103)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at io.openmessaging.benchmark.worker.BenchmarkWorker.main(BenchmarkWorker.java:77)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.AttributeContainerMap
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Jul 24 19:53:35 ip-10-0-0-76.us-west-2.compute.internal benchmark-worker[3985]: ... 4 more
```

**Comment by rahulpandeycs** [comment]
There is a mismatch in the pom dependency version of jett-util with jetty server. Please replace jetty-util dependency with below:
```
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-util</artifactId>
			<version>9.4.35.v20201120</version>
		</dependency>
```
