### ISSUE TITLE
Errors running Kafka benchmark

### ISSUE THREAD

**Issue by david-streamlio** [openmessaging/openmessaging-benchmark#36]
23:56:18.846 [kafka-producer-network-thread | producer-3] WARN - Write error on message
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.TimeoutException: Expiring 125 record(s) for test-topic-O1HToMc-0000-11: 30129 ms has passed since batch creation plus linger time
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_161]
	at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkProducer.lambda$sendAsync$0(KafkaBenchmarkProducer.java:46) ~[io.openmessaging.benchmark-driver-kafka-0.0.1-SNAPSHOT.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:204) [org.apache.kafka-kafka-clients-1.0.0.jar:?]
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:187) [org.apache.kafka-kafka-clients-1.0.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:627) [org.apache.kafka-kafka-clients-1.0.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:287) [org.apache.kafka-kafka-clients-1.0.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:238) [org.apache.kafka-kafka-clients-1.0.0.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:176) [org.apache.kafka-kafka-clients-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by Hellojungle** [comment]
Could you tell me the env and command you used so i can reproduce it?

**Comment by david-streamlio** [comment]
These errors occurred when I was running the benchmark on my MacBook Pro. I used the default settings for everything and didn't modify any configurations.

I don't remember the exact test that was running at the time the above error occurred.

**Comment by david-streamlio** [comment]
I am unable to reproduce this error with the latest version of the code. Please close this issue
